import os
import json
import requests

def generate_supervisor_report(events: list, violations: int, coding_scores: dict, exam_duration: int) -> dict:
    """
    Acts as an AI Proctoring Supervisor. Analyzes the raw logs generated by the client 
    (MediaPipe WebAssembly) and intelligently synthesizes them into a human-readable 
    assessment report preventing strict false positives.
    """
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        return {
            "probability_cheating": "Unknown",
            "reasoning": "Agentic AI Supervisor disabled (Missing GEMINI_API_KEY). Proceed with standard manual review of logs.",
            "recommended_action": "Manual Review Required"
        }

    # Format the data for the LLM
    log_summary = "\\n".join([f"[{e.get('timeStr', '00:00:00')}] {e.get('type')}: {e.get('msg')}" for e in events])
    coding_summary = ", ".join([f"Q{k}: {v}%" for k,v in coding_scores.items()]) if coding_scores else "No coding questions attempted."

    prompt = f"""
    You are an expert AI Exam Supervisor. Review the following student's telemetry data from a {exam_duration} second exam.
    The data was generated real-time by a local computer vision hook.

    --- EXAM TIMELINE LOGS ---
    {log_summary if log_summary else 'No events recorded. Perfect behavior.'}
    
    Total Hard Violations: {violations}
    Coding Scores: {coding_summary}
    --------------------------

    Your task is to act as a reasonable, intelligent human proctor.
    1. Read the timeline of events. Are they repetitively looking offscreen or frequently switching tabs?
    2. Contextualize the coding scores vs behavior: Do the timeline alerts align with them looking at a split screen or writing code?
    3. Synthesize the raw data into a narrative paragraph evaluating the true risk. Do not simply regurgitate the logs.

    Return ONLY a valid JSON object matching the following structure exactly (no markdown formatting, no comments):
    {{
        "probability_cheating": "High" | "Medium" | "Low" | "None",
        "reasoning": "Your detailed 2-3 sentence paragraph reasoning here...",
        "recommended_action": "Pass" | "Review Timeline" | "Invalidate Exam"
    }}
    """

    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro:generateContent?key={api_key}"
    headers = {"Content-Type": "application/json"}
    payload = {
        "contents": [{
            "parts": [{"text": prompt}]
        }],
        "generationConfig": {
            "temperature": 0.2,
            "responseMimeType": "application/json"
        }
    }

    try:
        response = requests.post(url, headers=headers, json=payload, timeout=12)
        response.raise_for_status()
        
        data = response.json()
        candidates = data.get("candidates", [])
        if not candidates:
            raise ValueError("No response from Gemini")
            
        text = candidates[0]["content"]["parts"][0]["text"].strip()
        
        # Parse output JSON safely
        # Sometimes Gemini still wraps in ```json
        if text.startswith("```json"):
            text = text[7:]
        if text.endswith("```"):
            text = text[:-3]
            
        return json.loads(text.strip())
        
    except Exception as e:
        return {
            "probability_cheating": "Error",
            "reasoning": f"Agentic AI failed to process the request due to network or parsing error: {str(e)}",
            "recommended_action": "Manual Review Required"
        }
