import os
import json
import requests

_ALLOWED_PROBABILITIES = frozenset({"High", "Medium", "Low", "None"})
_ALLOWED_ACTIONS = frozenset({"Pass", "Review Timeline", "Invalidate Exam"})


def _normalize_supervisor_report(raw: dict) -> dict:
    probability = raw.get("probability_cheating", "Low")
    if probability not in _ALLOWED_PROBABILITIES:
        probability = "Low"

    reasoning = raw.get("reasoning", "")
    if not isinstance(reasoning, str) or not reasoning.strip():
        reasoning = "No explanation was generated. Please review timeline manually."
    else:
        reasoning = reasoning.strip()

    action = raw.get("recommended_action", "Review Timeline")
    if action not in _ALLOWED_ACTIONS:
        action = "Review Timeline"

    return {
        "probability_cheating": probability,
        "reasoning": reasoning,
        "recommended_action": action,
    }


def generate_supervisor_report(events: list, violations: int, coding_scores: dict, exam_duration: int) -> dict:
    """
    Acts as an AI Proctoring Supervisor. Analyzes the raw logs generated by the client 
    (MediaPipe WebAssembly) and intelligently synthesizes them into a human-readable 
    assessment report preventing strict false positives.
    """
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        return {
            "probability_cheating": "Unknown",
            "reasoning": "Agentic AI Supervisor disabled (Missing GEMINI_API_KEY). Proceed with standard manual review of logs.",
            "recommended_action": "Manual Review Required"
        }

    # Format the data for the LLM
    log_summary = "\\n".join([f"[{e.get('timeStr', '00:00:00')}] {e.get('type')}: {e.get('msg')}" for e in events])
    coding_summary = ", ".join([f"Q{k}: {v}%" for k,v in coding_scores.items()]) if coding_scores else "No coding questions attempted."

    prompt = f"""
    Use Case 1 — Agentic AI Assessment & Proctoring Platform
    (MCQ + Coding | Continuous | Secure | Explainable)

    Business Context:
    Organizations and ed-tech platforms need credible, scalable remote assessments that test real skills.

    Current Problems to avoid:
    - MCQ-only assessments are easy to game.
    - Coding evaluations often lack real-time monitoring.
    - Human-only proctoring does not scale.
    - Auditability and explainability are often weak.

    Business Goal:
    - Assess knowledge + problem solving in MCQ + coding.
    - Stay compatible with Python, Java, and SQL coding workflows.
    - Continuously monitor behavior and support real-time decisions.
    - Keep humans in control for high-risk cases.
    - Produce auditable, explainable outcomes.

    You are the Agentic AI Supervisor. Review the following student's telemetry data from a {exam_duration} second exam.
    The data was generated real-time by a local computer vision pipeline.

    --- EXAM TIMELINE LOGS ---
    {log_summary if log_summary else 'No events recorded. Perfect behavior.'}
    
    Total Hard Violations: {violations}
    Coding Scores: {coding_summary}
    --------------------------

    Your task is to act as a reasonable, intelligent human proctor.
    1. Read the timeline of events. Detect meaningful behavior patterns (frequent offscreen gaze, tab switching, repeated no-face, suspicious objects).
    2. Contextualize coding scores vs behavior: separate normal coding behavior from likely cheating.
    3. Synthesize the raw data into an explainable narrative paragraph evaluating true risk. Do not simply regurgitate logs.
    4. Be conservative with high-risk outcomes and prefer "Review Timeline" when human review is appropriate.

    Return ONLY a valid JSON object matching the following structure exactly (no markdown formatting, no comments):
    {{
        "probability_cheating": "High" | "Medium" | "Low" | "None",
        "reasoning": "Your detailed 2-3 sentence paragraph reasoning here...",
        "recommended_action": "Pass" | "Review Timeline" | "Invalidate Exam"
    }}
    """

    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-pro:generateContent?key={api_key}"
    headers = {"Content-Type": "application/json"}
    payload = {
        "contents": [{
            "parts": [{"text": prompt}]
        }],
        "generationConfig": {
            "temperature": 0.2,
            "responseMimeType": "application/json"
        }
    }

    try:
        response = requests.post(url, headers=headers, json=payload, timeout=12)
        response.raise_for_status()
        
        data = response.json()
        candidates = data.get("candidates", [])
        if not candidates:
            raise ValueError("No response from Gemini")
            
        text = candidates[0]["content"]["parts"][0]["text"].strip()
        
        # Parse output JSON safely
        # Sometimes Gemini still wraps in ```json
        if text.startswith("```json"):
            text = text[7:]
        if text.endswith("```"):
            text = text[:-3]

        parsed = json.loads(text.strip())
        if not isinstance(parsed, dict):
            raise ValueError("Gemini response is not a JSON object")

        return _normalize_supervisor_report(parsed)
        
    except Exception as e:
        return {
            "probability_cheating": "Error",
            "reasoning": f"Agentic AI failed to process the request due to network or parsing error: {str(e)}",
            "recommended_action": "Manual Review Required"
        }
